### ISSUE TITLE
Display link checking statistics in alphabetical order by collection

### ISSUE THREAD

**Issue by wowasa** [clarin-eric/clarin-curation-module#104]
Currently we have the table with the over results on the top. After this a table, containing the results by collection. These tables are randomly ordered and should be in an alphabetical order instead.

**Comment by twagoo** [comment]
If I can make a suggestion, it would also be nice if there were some kind of index or selection mechanism so that you could quickly see whether a specific collection is there, and go to it without a lot of scrolling.

**Comment by wowasa** [comment]
done for 5.2.0
