### ISSUE TITLE
Save a report history 

### ISSUE THREAD

**Issue by wowasa** [clarin-eric/clarin-curation-module#109]
Currently each run of curation update overrides to reports of the previous run. Hence the simplest way to have a report history is to add a timestamp to the filename of each report and to assure that the results of the latest report are displayed.

**Comment by twagoo** [comment]
A nice addition would be to have two links on top of each report:
- link to the latest report for this collection (i.e. 'current' version which is overwritten every time)
- permalink to this version of the report (i.e. timestamped filename)

**Comment by wowasa** [comment]
> A nice addition would be to have two links on top of each report:
> 
>     * link to the latest report for this collection (i.e. 'current' version which is overwritten every time)
> 
>     * permalink to this version of the report (i.e. timestamped filename)

this is actually not where we have agreed on: version 5.3.0 should have a roll over mechanism to save the previous report files with a timestamp. I the next step we want to discuss if and how we're going to use and present different results.

**Comment by twagoo** [comment]
> this is actually not where we have agreed on: version 5.3.0 should have a roll over mechanism to save the previous report files with a timestamp. I the next step we want to discuss if and how we're going to use and present different results.

Sure, I don't think my suggestion is in conflict with that decision. But I agree that it would be better to make it into a separate follow-up issue - and then still discuss whether we want to present things like that or not.

**Comment by wowasa** [comment]
done! 
Instead of a rollover I'm creating a copy with »report generation date« in filename, which follows the pattern:
<report name>_yyyy-mm-dd.<suffix>. 
A rollover with a date from file attributes would lead to files with a different timestamp after midnight
