### ISSUE TITLE
TSV export broken

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/clarin-curation-module#116]
Report for https://curation.clarin.eu/collection/table v 5.2.2

After a nr of elements it seems \n rather than \t is used as separator, eg 

Name	Score	Num Of Records	Num Of Profiles	Num Of Unique Links	No Of Checked Links	Ratio Of Valid Links	Avg Num Of Res Proxies	Num Of Res Proxies	Ratio Of Valid Records	Avg Num Of Empty XML Elements	Ratio Facets Non Zero	LanguageCode	Collection	ResourceClass	Modality	Format	Keywords	Genre	Subject	Country	Organisation	Name	Description	License	Availability
DARIAH_DE_Repository	0.5754604621474214	561	1	561	320	1.0	1.0	561	1.0	5.0	0.21428571428571427	
                0.0
            	
                0.0
            	
                0.0
            	
                0.0
            	
                0.0
            	
                0.0
            	
                0.0
            	
                0.0
            	
                0.0
            	
                0.0
            	
                0.0
            	
                0.3868092691622103
            	
                0.1051693404634581
            	
                0.10338680926916222

**Comment by wowasa** [comment]
Apparently the error is not in the stylesheet which is used to transform the JAXB report to tsv but has its cause in the use of Saxon 9.8.0-15 which is loaded via transitive dependency of vlo-importer through curation-core. 
I have to check whether on upgrade of Saxon brings the expected result or whether we should just use the transformer class of jdk instead

**Comment by wowasa** [comment]
fixed. Updated dependency to saxon and modified stylesheet to use apply-templates instead of nested for-each (the last only for convenience)
