### ISSUE TITLE
HTTP status 405 shouldn't be rated as "Broken Link"

### ISSUE THREAD

**Issue by teckart** [clarin-eric/clarin-curation-module#29]
The link checker currently rates URLs that don't support GET requests as "Broken Link". This is for example the case for every service URL of the WebLicht framework which has to be specified in the respective CMDI record.

Example-URL: [http://clarinws.informatik.uni-leipzig.de:8080/clarinwebservices/frequency/11022/0000-0000-2435-C/frequencytcf04](http://clarinws.informatik.uni-leipzig.de:8080/clarinwebservices/frequency/11022/0000-0000-2435-C/frequencytcf04)

**Comment by coy123** [comment]
Hello,

Sorry for the delayed answer. I wasn't getting notifications for github issues for this repo.

We are currently discussing how to deal with these type of links. The proposed solution is to regard them as undetermined and not include them in the final score. I will update the issue as soon as we decide and implement the solution.

Considered status codes are:
405 - Method not allowed
401 - Unauthorized
403 - Forbidden (maybe)

If you want to suggest other codes that would be in this category. Feel free to suggest it.

**Comment by coy123** [comment]
After some discussion, we will consider the following as "undetermined" URLs:

403 - Fordbidden
405 - Method Not Allowed
429 - Too Many Requests

**Comment by coy123** [comment]
Implemented on new release. Will go online next week.
