### ISSUE TITLE
Correct and uniform usage of ratios/percentages

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/clarin-curation-module#37]
In the collection report we find:
 
```
modality | 0.5663
```
```
Ratio valid Records: 0.9880
```
```
Average rate of populated elements: 0.9835%
```

I would suggest changing all of these to proper percentages with reasonable precision, for example in these cases 56.6%, 98.8% and 98.4%

**Comment by twagoo** [comment]
This also applies to the other reports, which more consistently use ratios.

**Comment by wowasa** [comment]
I'm working on this issue since I realized that we have a mixture of English and German number format on profiles and collections overview

**Comment by wowasa** [comment]
changing HTML view as follows
* all ratios become percentage with two digits after the decimal point
* remaining floating point numbers have four digits after the decimal point
* use of decimal point instead of comma
* all numbers right aligned

is there any objection???

**Comment by wowasa** [comment]
I forgot to mention that everything will be deployed with curation 2.3 next week (first week of March)
