### ISSUE TITLE
Exception in tooltips

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/clarin-curation-module#38]
The instance assessment form as well as the profiles and colletions tables show a stacktrace (`StringIndexOutOfBoundsException`) in the tooltip when hovering over any of the cells.

**Comment by twagoo** [comment]
After a reload I could not reproduce. In fact, I don't get any tooltips. Maybe the application got into a weird state.

**Comment by wowasa** [comment]
I guess we have to refactor the vaadin part of the web-app anyway. The upgrade from vaadin 7 to 8 is using a transitory package which marks most methods as deprecated. Since we agreed on adding some help, we will do it a.s.p

**Comment by coy123** [comment]
Closing as we replaced Vaadin.
