### ISSUE TITLE
Link to download XML report

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/clarin-curation-module#39]
Would it be possible to have (and somewhere in the application provide) a URL that leads to the XML report for a collection, profile or instance? This would be helpful for sharing purposes, e.g. in the context of the centre assessment.

**Comment by coy123** [comment]
Collection and profiles wouldn't be an issue. But with instances it might be a problem: We would need a lot of disk space after a while. Do we want to save and make available all instance reports or can we delete them after a certain period of time?

**Comment by twagoo** [comment]
Would it be possible to generate them on the fly? And maybe cache them for a few days or so. I can see how this could lead to a relatively long response time in some cases but that doesn't have to be too problematic.

**Comment by coy123** [comment]
What is an appropriate amount of time to have the Instance reports available before deleting them?

**Comment by twagoo** [comment]
If it's possible to re-generate them on request, I don't think more than a day would be necessary. Otherwise, the time that is the regular interval between checks?

**Comment by coy123** [comment]
Ok, Wolfgang wants to make sure that Instance reports that we will make available are the ones that come through the web app GUI and not every instance in collections. That would make collection report generation take forever. Have we understood correctly?

Also, by "re-generate them on request", do you mean re-generate them on a GET request on the URL or a request of instance report generation through the web app? In the former option, we would need to save the instance records to be able to regenerate the reports which totally defeats the purpose of saving space.

Finally, then 24 hours is the time limit I would implement for instance report life span.

**Comment by twagoo** [comment]
That would be a good approach: you have to go through the GUI to get an instance assessed, and only then you get a link. If this link expires, this has to be made clear. So indeed, lazy report generation.

For re-generating on request, I was thinking of reports of online records (so assess by URL). But indeed, these can potentially be moving targets. So maybe keep it simple and only do it for manually assessed records. 

In any case, for existing use cases such as centre assessment the collection reports are more relevant anyway (I think).

**Comment by coy123** [comment]
Now collection, instance and profile reports all have URLs associated with them. They are to be found in the root element as attribute in the xml reports and they are also to be found in the GUI. Keep in mind that Instance reports older than 24 hours are deleted everyday at 03:00 Vienna time, which means a subsequent request would return 404 and the instance record needs to be curated again (either through drag and drop or giving a URL to the record).
