### ISSUE TITLE
Make link checking reports downloadable as data (XML/JSON)

### ISSUE THREAD

**Issue by teoric** [clarin-eric/clarin-curation-module#51]
The HTML rendering of, e.g., the link checking is great.  I would find it even easier if the data were available as JSON or XML as this would facilitate analysis in case of large numbers by, e.g. grouping by message rather than code only.  Given that the HTML seems to be incrementally loaded, just downloading that is also not an option.

(Maybe I am missing something but I do not find an address to ask a question to, so this seems to be the preferred mode of communication?)

**Comment by coy123** [comment]
We know about this issue and it is on our to do list. With few links, the html render is more than adequate but for larger sizes, it is not really viable to facilitate analysis as you mention. I will report back when the feature (a way to download all links in a list) is ready.

Also yes, this is the preferred mode of communication as the Feedback button leads here. Thanks for reporting the issue. :)

**Comment by teoric** [comment]
Thank **you**, looking forward to XML, JSON or other IT argo(t)(nautics).

**Comment by twagoo** [comment]
Note that collection and profile reports are already downloadable as XML (link included in the HTML rendering for individual profiles/collections)

**Comment by twagoo** [comment]
Succeeded by #63
