### ISSUE TITLE
What do the flags mean under Facet Section in Record report?

### ISSUE THREAD

**Issue by coy123** [clarin-eric/clarin-curation-module#56]
When validating a record and generating a report, there are two flags under the facet section with different colors:
⚑ - Derived Facet
⚑ - Value Mapping 
These don't seem to be used in the following table, so what do they mean?

**Comment by wowasa** [comment]
derived facets are defined in facetConcepts.xml, value mappings by ValueMappings.xml. Both features are currently not used
