### ISSUE TITLE
update FAQ

### ISSUE THREAD

**Issue by coy123** [clarin-eric/clarin-curation-module#58]
It is currently found on google sheets here: https://docs.google.com/spreadsheets/d/18EyqXjL5-e7tc0kpvTHQNaG5ObXr_WNIfdvrcJRiTAg/edit?usp=sharing

This table should be added into the faq.

**Comment by wowasa** [comment]
should also be updated to explain the scoring

**Comment by wowasa** [comment]
done but since the insert of faq.md is hard coded in java script and points to the github master branch the updated faq is only visible in the dev branch unless version 5.2.0 is pushed to the master branch
