### ISSUE TITLE
Show total number of urls on the link checking statistics URLs table

### ISSUE THREAD

**Issue by coy123** [clarin-eric/clarin-curation-module#62]
Directly under  or next to the collection name.

So when clicking on Ok on TLA, it should say x amount of links to show that this collection has this many links with this category,

For example on this page: https://curate.acdh.oeaw.ac.at/statistics/The_Language_Archive/Ok next to "The Language Archive", it can say Total:xxx

**Comment by wowasa** [comment]
done for v5.2.0
