### ISSUE TITLE
Add option to download link checking detail list as XML, JSON and TSV

### ISSUE THREAD

**Issue by coy123** [clarin-eric/clarin-curation-module#63]
Some lists have thousands of links in the link checking statistics view. Therefore I propose to have a button to download an csv report of the full list. This way, users can have the full list and can run automatic tools on it if they wish.

There needs to be a solution for huge data. Some pages have millions of links.

Formats: 
* CSV or TSV
* XML
* JSON

**Comment by wowasa** [comment]
done for v. 5.2.0
