### ISSUE TITLE
webapp creates two connection pools with same properties

### ISSUE THREAD

**Issue by wowasa** [clarin-eric/clarin-curation-module#73]
log file shows the two CPs are created with identical properties

**Comment by wowasa** [comment]
apparently the method contextInitialized of class ApplicationInit is called twice

**Comment by twagoo** [comment]
This made me curious and I had a look at how this is designed, and I think it would be a very good idea to refactor the `Configuration` class and how it's used, i.e. get rid of as much of the static stuff as possible. In my opinion, it would be better to have a single configuration instance that is looked up or injected, but let it be a proper object that knows whether it has been initialised or not.

A quick workaround would be to have a flag for initialised state and deal with this in a thread safe manner...

**Comment by wowasa** [comment]
no bug - the application is just twice installed on our test server :-(
