### ISSUE TITLE
Sanitize input for `/record` path

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/clarin-curation-module#79]
The call defined in [Record.java](https://github.com/clarin-eric/clarin-curation-module/blob/5.0.5-1/curation-module-web/src/main/java/eu/clarin/routes/Record.java) takes a file path as input. Ensure that this path resolves to an existing record under control of the curation module (i.e. existing in `Configuration.RECORDS_PATH`) before continuing to process the request.

**Comment by wowasa** [comment]
this is not an issue since this is the case already the case (see line 26 of Records.java)

**Comment by twagoo** [comment]
I think we are relying on the assumption that relative paths cannot be provided as a parameter because of the way request paths are pre-processed by the JAX-RS framework. I.e. the `filepath` variable can never contain `../`. But this is too brittle in my opinion, and I suspect there could be workarounds. In any case it has to be documented as a pre-condition as long as we make this assumption.

**Comment by wowasa** [comment]
a fix was deployed with version 5.6
