### ISSUE TITLE
Include 'development' status profiles

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/clarin-curation-module#88]
Currently only the default list of profiles is evaluated (https://catalog.clarin.eu/ds/ComponentRegistry/rest/registry/profiles).

Published profiles with 'development' status should be included as well. A [list can be retrieved](https://catalog.clarin.eu/ds/ComponentRegistry/rest/registry/profiles?&status=production&status=development) by adding `status` query parameters:
```
https://catalog.clarin.eu/ds/ComponentRegistry/rest/registry/profiles?&status=production&status=development
```

It would be nice to mark the status (`DEVELOPMENT` or `PRODUCTION`) in the front end.

**Comment by wowasa** [comment]
changed URL parameters in class PublicProfiles, line 25 from 
registrySpace=published&status=production
to 
registrySpace=published&status=production&status=development

Modification is going to be deployed in production with v5.1. by the end of June

**Comment by wowasa** [comment]
implemented in v. 5.1.0
