### ISSUE TITLE
Overall linkchecker statistics created BEFORE link confirmation

### ISSUE THREAD

**Issue by wowasa** [clarin-eric/clarin-curation-module#89]
The overall linkchecker report is generated when the class LinkcheckerReport is instantiated (eu.clarin.cmdi.curation.reportLinkCheckerReport, line 23). This means the overall report is generated BEFORE processing the CMDI files, based on the data of the last run, while the current run is deactivating non confirmed links and inserting new ones. 

Instead curation must assure that the overall statistics is created AFTER all CMDI files have been processed. 

In curation 5.1 this has also an impact on the whole program since, because of the joins, the overall statistics is an heavy database operation which takes up to have a minute and prevents the instantiation of the  class LinkcheckerReport

**Comment by twagoo** [comment]
For reference, this is the offending part: the [constructor of `LinkCheckerReport#Overall`](https://github.com/clarin-eric/clarin-curation-module/blob/master/curation-module-core/src/main/java/eu/clarin/cmdi/curation/report/LinkCheckerReport.java#L116-L142). 

We need to check the entire code for other cases where data classes and logic are intermingled too closely. We should make absolutely sure that no substantial logic is executed in any of the constructors, in particular not in data classes.

**Comment by wowasa** [comment]
fixed in v. 5.1.0
