### ISSUE TITLE
review link processing in dashboard update

### ISSUE THREAD

**Issue by wowasa** [clarin-eric/clarin-curation-module#96]
New database design with need to save links serially doubled processing time of the dashboard update from formally three to six hours. We have either to speed the way we are saving link or to decouple ling saving and link checker statistics from reports generation.

**Comment by twagoo** [comment]
For the record, on production the dashboard update currently seems to take 3.5 hours in total.

**Comment by wowasa** [comment]
one idea is to de-connect reports processing from link processing by just writing LinkToBeChecked to a queue which is processed independently. At the end waits for a notification from the queue processor and generates link checker statistics as soon as the the queue is processed

**Comment by wowasa** [comment]
did some grouping per CMD file in version 5.2 but the major step will be after the implemenation of spring-jpa in rasa

**Comment by wowasa** [comment]
done for 5.2.0: modifications in rasa save method for synchronization
